# Generated by Django 4.2.3 on 2023-10-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_callrecording_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callrecording',
            name='audio_sample',
            field=models.FileField(upload_to='audio_samples'),
        ),
    ]
